apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: book-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-deployment
  template:
    metadata:
      labels:
        app: book-deployment
    spec:
      containers:
        - name: book-deployment
          image: 'paulodhiambo/kyosk:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri-secret
                  key: MONGO_URI
      restartPolicy: Always