apiVersion: v1
kind: Secret
metadata:
  name: mongo-uri-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYnMrc3J2Oi8vYXBpOmRyWUQ4TzQ4cHhRSnJ3Vm9AY3VyaW9jaXRpLm5lcHZ2Lm1vbmdvZGIubmV0L3Rlc3Q/cmV0cnlXcml0ZXM9dHJ1ZSZhcHBOYW1lPWN1cmlvY2l0aQ==
